---
title: "DataFrame_Vol.2"
author: "Ziyade CHABI MACO"
date: "2024-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R prog.exercise
```{r sort_runtime}
# link1: R exercise
# Exercise 1: Dataframe showing
Id <- rep(1:4, each = 3)
Letter <- rep(letters[1:3], times = 4)
x <- seq(1, 43, along.with = Id)
y <- seq(-20, 0, along.with = Id)
df <- data.frame(Id, Letter, x, y)
df


```


```{r sort_runtime}
## link1: R exercise
# Exercise2: Adding  x.a,x.b,y.a,y.b
x <- seq(1, 43, along.with = Id)
y <- seq(-20, 0, along.with = Id)
df_wide <- reshape(df, idvar = "Id", timevar = "Letter", direction = "wide")
df_wide


```


```{r sort_runtime}
## link1: R exercise
# Exercise3: Two dataframe creating
df1 <- data.frame(Id = 1:4, Age = c(14, 12, 15, 10))
df2 <- data.frame(Id = 1:4, Sex = c("F", "M", "M", "F"), Code = letters[1:4])
M <- merge(df1, df2, by = "Id")
M


```


```{r sort_runtime}
# link1: R exercise
# Exercise 4: Adding 
df1 <- data.frame(Id = 1:4, Age = c(14, 12, 15, 10))
df2 <- data.frame(Id = 1:4, Sex = c("F", "M", "M", "F"), Code = letters[1:4])
M <- merge(df1, df2, by = "Id")
df3 <- data.frame(id2 = 4:1, score = c(100, 98, 94, 99))
N <- merge(M, df3, by.x = "Id", by.y = "id2")
N


```


```{r sort_runtime}
# link1: R exercise
# Exercise 5: Reduce and create a new dataframe
#1.
N_reduced <- N[, !(names(N) %in% c("Sex", "Code"))]
N_reduced

#2. Creating
values <- unlist(N_reduced)
ind <- rep(names(N_reduced), each = nrow(N_reduced))
df_new <- data.frame(values, ind)
df_new


```


```{r trees}
## link1: R exercise
# Exercise 6: Dataset trees

library(dplyr)

#a) Ensure trees is a data frame:
data("trees")
trees <- as.data.frame(trees)
print(class(trees))
trees
```
```{r trees}
#b) Create a new data frame A:
A <- data.frame(
  Girth = c(mean(trees$Girth), min(trees$Girth), max(trees$Girth), sum(trees$Girth)),
  Height = c(mean(trees$Height), min(trees$Height), max(trees$Height), sum(trees$Height)),
  Volume = c(mean(trees$Volume), min(trees$Volume), max(trees$Volume), sum(trees$Volume)),
  row.names = c("mean_tree", "min_tree", "max_tree", "sum_tree")
)
A

```


```{r order cols}
## link1: R exercise
# Exercise 7: Ordering cols
# Charger la bibliothèque dplyr
library(dplyr)
A <- data.frame(
  Girth = c(mean(trees$Girth), min(trees$Girth), max(trees$Girth), sum(trees$Girth)),
  Height = c(mean(trees$Height), min(trees$Height), max(trees$Height), sum(trees$Height)),
  Volume = c(mean(trees$Volume), min(trees$Volume), max(trees$Volume), sum(trees$Volume)),
  row.names = c("mean_tree", "min_tree", "max_tree", "sum_tree")
)
# 1) Trier le data frame par la première colonne (Girth)
A_ordered <- A %>%
  arrange(Girth)

# Afficher le data frame trié
print("Data frame A trié par Girth:")
print(A_ordered)

# 2) Renommer les row names : mean_tree -> mean, min_tree -> min, etc.
# Récupérer les noms des lignes
rownames(A_ordered) <- c("mean", "min", "max", "tree")

# Afficher le data frame avec les noms de lignes modifiés
print("Data frame A avec row names renommés:")
print(A_ordered)



```


```{r empty df}
# link1: R exercise
# Exercise 8: Creating an empty data frame with column types
df <- data.frame(Ints = integer(), Logicals = logical(), Doubles = double(), Characters = character())
str(df)


```


```{r duplicate items}
# link1: R exercise
# Exercise 9: Display,detect duplicate item and display rest item 
# Charger la bibliothèque dplyr
library(dplyr)

# Créer le data frame XY
XY <- data.frame(
  X = c(1, 2, 3, 1, 4, 5, 2),
  Y = c(0, 3, 2, 0, 5, 9, 3)
)

# Afficher le data frame XY
print("Data frame XY:")
print(XY)

# 1) Identifier les lignes dupliquées
duplicated_elements <- duplicated(XY)
print("Duplicated elements (TRUE indique les lignes dupliquées):")
print(duplicated_elements)

# Afficher les lignes dupliquées
print("Lignes dupliquées:")
print(XY[duplicated_elements, ])

# 2) Garder uniquement les lignes uniques
XY_unique <- distinct(XY)

# Afficher le data frame unique
print("Data frame XY avec uniquement les lignes uniques:")
print(XY_unique)



```


```{r sort_runtime}
# link1: R exercise
# Exercise 10:
library(dplyr)
library(tidyr)

# a) Utiliser le dataset 'Titanic' et le convertir en data frame
data("Titanic")
df_titanic <- as.data.frame(Titanic)

# Vérifier la classe
print(class(df_titanic))

# Afficher les premières lignes du dataset Titanic
print(head(df_titanic))

# b) Définir un data frame avec les conditions spécifiées
# Filtrer pour Class == "1st" et Survived == "No"
df_filtered <- df_titanic %>%
  filter(Class == "1st" & Survived == "No") %>%
  select(Sex, Age, Freq)

# Afficher le data frame résultant
print("Data frame avec Class = '1st' et Survived = 'No':")
print(df_filtered)

```
